version: '3'
services:
  apache:
    image: "httpd:2.4"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/:/usr/local/apache2/htdocs/"
      - "./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./conf/mime.types:/usr/local/apache2/conf/mime.types"

